### PR TITLE
Update README.md (Login with an already existing account)

### PR DESCRIPTION
**Pull request by Systemac**
update Weward.py to correctly read the token,
add request_account.py to retrieve an account already created.

### CODE REVIEW

**Comment by Tkd-Alex** [comment]
> Now, I have to understand how you got access to all the api of weward, it still remains a mystery, I thought of reverse engineering by decompiling the apk, but I have not yet launched in it ....

https://github.com/shroudedcode/apk-mitm
https://www.charlesproxy.com/

**Comment by Systemac** [comment]
> > Now, I have to understand how you got access to all the api of weward, it still remains a mystery, I thought of reverse engineering by decompiling the apk, but I have not yet launched in it ....
> 
> https://github.com/shroudedcode/apk-mitm https://www.charlesproxy.com/

Wo, I didn't know, thanks to you!

**Comment by Tkd-Alex** [comment]
> And if there is a need to modify something on the commit, tell me, I will correct it for the next time (if there is one)

Look at my review :)

**Comment by Systemac** [comment]
Sorry but, where can look at your review ???

**Comment by Systemac** [comment]
> https://github.com/Tkd-Alex/WeWard-Miner/pull/3/files

Ok but i don't see any comments or reviews....

**Comment by Tkd-Alex** [comment]
Really?
image

**Comment by Systemac** [comment]
image
really...

**Review by Tkd-Alex — CHANGES_REQUESTED** [review]

**Review by Tkd-Alex — APPROVED** [review]

**Pull request merged**
